version: '3.1'


services:

  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    volumes:
    - /var/lib/grafana
  
  prometheus:
    image: prom/prometheus
    expose:
    - "9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
      image: prom/pushgateway
      ports:
      - "9091:9091"

